# Generated by Django 5.0.7 on 2024-08-18 21:31

import django.db.models.deletion  # For handling deletion behaviors
import django_countries.fields  # For handling country fields
from django.conf import settings  # For accessing project settings
from django.db import migrations, models  # Django migration and model utilities


class Migration(migrations.Migration):

    initial = True  # This is the initial migration for the UserProfile model

    dependencies = [
        # Ensures that the user model is available before this migration runs
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                # AutoField for primary key ID
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Default phone number, optional
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                # Default street address line 1, optional
                ('default_street_address1', models.CharField(blank=True, max_length=80, null=True)),
                # Default street address line 2, optional
                ('default_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                # Default town or city, optional
                ('default_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                # Default county, optional
                ('default_county', models.CharField(blank=True, max_length=80, null=True)),
                # Default postcode, optional
                ('default_postcode', models.CharField(blank=True, max_length=20, null=True)),
                # Default country, optional, uses CountryField for ISO 3166-1 codes
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                # OneToOneField linking UserProfile to the custom User model
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
