# Generated by Django 5.0.7 on 2024-08-16 11:08

import django_countries.fields  # Third-party imports
from django.db import migrations  # Local imports


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
            # This change standardizes the country field to store ISO 3166-1 alpha-2 codes.
        ),
    ]
